repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
  - id: insert-license
    name: Add license for all python files
    exclude: ^(\.github|examples)/.*$
    types: [python]
    args:
    - --comment-style
    - "|#|"
    - --license-filepath
    - templates/LICENSE.txt
    - --fuzzy-match-generates-todo
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: local
  hooks:
  - id: unittest
    name: unittest
    entry: python -m unittest discover
    language: python
    args: ["tests"]
    pass_filenames: false
    stages: [commit]
