repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    - id: insert-license
      name: Add license for all python files
      exclude: ^(\.github|examples)/.*$
      types: [python]
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - templates/LICENSE.txt
        - --fuzzy-match-generates-todo
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
